### PR TITLE
Fix allmusic

### PR DESCRIPTION
**Pull request by marc2k3**
Impossible to debug this so it'll have to go

### CODE REVIEW

**Comment by marc2k3** [comment]
Hold off on this. If I save the html source to a text file and try parsing that, at least I'll get some errors to help me on my way.

**Comment by TheQwertiest** [comment]
>  any errors in the callback from the http request are silently swallowed

Yes, this is really annoying, but I can't do anything about it - corresponding ActiveXObject does not pass errors from callback. So even if callback ended up with failure and returned OHMYGODCRITICAL error code, there will be no indication about it anywhere...

**Comment by marc2k3** [comment]
You copied JSP code which doesn't work in SMP. You can't get `itemprop` from a `div` but `className` works so use that.

**Comment by marc2k3** [comment]
This is ready to merge now.

Dunno if you've been HA yet today but the latest nightly build is corrupting configs so all embedded scripts/settings etc are lost!!

**Comment by TheQwertiest** [comment]
> Dunno if you've been HA yet today but the latest nightly build is corrupting configs so all embedded scripts/settings etc are lost!!

Ouch... That... should not happen... Thanks for letting me know.

> This is ready to merge now.

Thanks!

**Pull request merged**
